services:
  api:
    container_name: whisper_janusz
    image: jj_whisper:3.0.0
    build: .
    ports:
      - "9000:8000"
    volumes:
      - ./app:/app/app
#    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]

    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: python -m uvicorn app.webservice:app --host 0.0.0.0 --port 8000 --reload
  api2:
    container_name: whisper_janusz2
    image: jj_whisper:3.0.0
    build: .
    ports:
      - "9001:8000"
    volumes:
      - ./app:/app/app
#    gpus: all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['1']
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=1
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    command: python -m uvicorn app.webservice:app --host 0.0.0.0 --port 8000 --reload
