services:
  
  # use api with gpu
  api:
    container_name: whisper_janusz
    image: whisper
    build:
      context: .
      args:
        USE_CUDA: true  # true or false 
    ports:
      - "${PORT}:8000"
    volumes:
      - ./app:/app/app
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - USE_CUDA=true
    env_file:
      - config.env       
    command: python -m uvicorn app.webservice:app --host 0.0.0.0 --port 8000 --reload

  # use api with cpu
  # api:
  #   container_name: whisper_janusz
  #   image: whisper
  #   build:
  #     context: .
  #     args:
  #       USE_CUDA: false
  #   ports:
  #     - "${PORT}:8000"
  #   volumes:
  #     - ./app:/app/app
  #   environment:
  #   - USE_CUDA=false   # true or false 
  #   env_file:
  #     - config.env      
  #   command: python -m uvicorn app.webservice:app --host 0.0.0.0 --port 8000 --reload